### ISSUE TITLE
Milestone 6 Priorities

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-firmware#204]
This milestone focuses on utilizing the 1MB SPI flash chip on the T400.

Goals:
- Implement the SPI flash input/output
- Offload data form the atmega32u4 chip onto the SPI flash chip

**Implement the SPI flash input/output**
- [ ] SPI flash #191
- [ ] SPI flash driver #210
- [ ] Implement SPI flash timeout #137

**Offload data form the atmega32u4 chip onto the SPI flash chip**
- [ ] Read graphic data from external memory #206
- [ ] Read SPI flash data from SD card #205
- [ ] MCP9800 calibration #15
- [ ] MCP3424 calibration #14
- [ ] Hold data points in SPI flash #208
- [ ] Lookup table in powers of two #209
- [ ] Remove all floating point operations #212
