### ISSUE TITLE
Milestone 7 priorities

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-firmware#207]
This milestone focuses on finishing the T400 current feature set. This entails fixing bugs and improving the user experience.

Goals
- Squash bugs
- Enhance current features for usability

**Bugs**
- [ ] When battery voltage too low, display wraps to full again #177
- [ ] Graph scaling for F and K #202

**Enhancements**
- [ ] Power-on delay #194
- [ ] Draw axis based on first reading #188
- [ ] Disabled button feedback #193
- [ ] Log file name method #190
