### ISSUE TITLE
Milestone 8 Priorities

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-firmware#211]
This milestone focuses on adding new features to the T400.

- Improved usability
- Enhanced performance
- New functionality

**Improved usability**
- [ ] Calibrate vbat readings #175
- [ ] Temperature data persistence #156

**Enhanced performance**
- [ ] File locations and quantities #195
- [ ] Sub 1s readings #169
- [ ] Sleep peripherals when idle #143
- [ ] MCP9800 temperature compensation #118

**New functionality**
- [ ] Button long-press alternate function #200
- [ ] Display min max avg #199
- [ ] Save state parameters to memory #163
- [ ] User configurable date/time #153
- [ ] RTC: Set RTC date/time #51
- [ ] Backlight brightness set with PWM #142
- [ ] User-adjustable backlight brightness #141
- [ ] Show large thermocouple readings #117
- [ ] Buttons: Button cycles through TC readings #48
- [ ] Power On Self Test #112
- [ ] Store battery info on external memory for estimation #90
- [ ] Add watchdog reset to OS in case of lockup. #65
- [ ] Configuration menu #59
- [ ] Calibration routine #54
- [ ] Read calibration data from SD card #35
- [ ] LCD: Display time since logging began #27

**Comment by charlespax** [comment]
No longer relevant. Closing issue.
